//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SlopeOperator
//  @ File Name : BookingController.java
//  @ Date : 15/02/2017
//  @ Author : Genaro Bedenko
//
//

package spherebookingsystem;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;
import java.util.Random;

/*
 *Class that contains all of the bookings
 *and performs the actions on the booking entity
 *
 * @author Genaro Bedenko
 */
public class BookingController {
    
        BookingRepoImpl BookingRepo = new BookingRepoImpl();
        
        
        // Function that takes in a customer id and session id
        // Creates a new instance of Booking() with the new attributes
        // Passes the object to the booking repo to write this to the database table
        public Booking book(Connection connection, int customerID, int sessionID, float bookingPrice, boolean customerPaidStatus, int numberOfSkiers){
             
            BookingFactory bookingFactory = new BookingFactory();
                
            Booking book = bookingFactory.createBooking(customerID,
                                                        sessionID,
                                                        bookingPrice,
                                                        customerPaidStatus,
                                                        numberOfSkiers);
            
            // Perform write in booking repo to add a new record
            BookingRepo.write(connection, "add", book);
             
            return(book);
        }          
}   