//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Session.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Session
{
   protected int id;
   private int startTime;
   private int endTime;
   private int slopeID;
   private int instructorID;
   private dateTime date;
   private int maxBookings;
   public void getId()
   {
   
   }
   
   public void getStartTime()
   {
   
   }
   
   public void getEndTime()
   {
   
   }
   
   public void getSlopeId()
   {
   
   }
   
   public void getInstructorId()
   {
   
   }
   
   public void getDate()
   {
   
   }
   
   public void getMaxBookings()
   {
   
   }
   
   public void setStartTime()
   {
   
   }
   
   public void setEndTime()
   {
   
   }
   
   public void setSlopeId()
   {
   
   }
   
   public void setInstructorId()
   {
   
   }
   
   public void setDate()
   {
   
   }
   
   public void setRecursion()
   {
   
   }
   
   public void setMaxBookings()
   {
   
   }
}
