//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SlopeRep.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class SlopeRep
{
   public void read()
   {
   
   }
   
   public void write()
   {
   
   }
}
