//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Booking.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Booking {
	public Integer customerID;
	public Integer sessionID;
}
