//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CheckIn OperatorUI.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class CheckIn OperatorUI {
	public CheckinOperator control;
	public char select task() {
	
	}
	
	public void input() {
	
	}
	
	public char displayResults() {
	
	}
}
