//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Session.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Session {
	public Object sessionTime;
	public Object sessionDate;
	public Object sessionInstructor;
}
