//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Booking Repo.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public interface Booking Repo {
}
