//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Slope Operator UI.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Slope Operator UI {
	private Object control Booking Controller;
}
