//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SessionRep.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class SessionRep {
	public Object Attribute1;
}
