//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Booking.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//
package bookingsession;

public class Booking {
    
	 private int customerID = -1;
         private int sessionID = -1;
        
         public int getCustomerID(){
             return customerID;
         }
         public void setCustomerID(int aRef){
             customerID = aRef;
         }
         public int getSessionID(){
             return sessionID;
         }
         public void setSessionID(int aName){
             sessionID = aName;
         }     
}
