//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Customer.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Customer {
	private Integer CustomerID;
	private String FirstName;
	private String LastName;
	private String Email;
	private String Telephone;
	public void getID() {
	
	}
	
	public void getName() {
	
	}
	
	public void getLastName() {
	
	}
	
	public void getEmail() {
	
	}
	
	public void getTelephone() {
	
	}
}
