//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BookingClass.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class BookingClass {
	public Integer customerID;
	public Integer sessionID;
	public void read() {
	
	}
}
