//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Check In Operator.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Check In Operator {
	public void enterCustomersId() {
	
	}
	
	public void seeSchedule() {
	
	}
	
	public void viewSessionDetails() {
	
	}
	
	public void confirmCheckIn() {
	
	}
	
	public void seeProfile() {
	
	}
}
