//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Customer.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Customer {
	public Integer ID;
	public String firstName;
	public String lastName;
	public String email;
	public String telephon;
}
