//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Booking Controller.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Booking Controller {
	private Object list Bookings;
	private void createBooking() {
	
	}
	
	public void viewBooking() {
	
	}
	
	public void updateBooking() {
	
	}
	
	public void deleteBooking() {
	
	}
}
