//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BookingDB Table.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class BookingDB Table {
	public void write() {
	
	}
	
	public void read() {
	
	}
}
