//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Receptionistgui.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Receptionistgui {
	public Object Attribute1;
	
	public class Bae, Rankyoung {
	}
}
