//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Session.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Session {
	private Integer SessionID;
	private Integer StartTime;
	private Integer EndTime;
	private String SessionType;
	private Integer NoOfPeople;
	private Integer InstructorID;
	public void getStartTime() {
	
	}
	
	public void getEndTime() {
	
	}
	
	public void getSessionType() {
	
	}
	
	public void getNumberOfPeople() {
	
	}
	
	public void getInstructorID() {
	
	}
}
