//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SlopeOperator
//  @ File Name : BookingController.java
//  @ Date : 15/02/2017
//  @ Author : Genaro Bedenko
//
//

package slopeoperator;

import java.sql.Connection;
import java.util.*;
import java.util.Random;

/*
 *Class that contains all of the bookings
 *and performs the actions on the booking entity
 *
 * @author Genaro Bedenko
 */
public class BookingController {
    
        BookingRepoImpl BookingRepo = new BookingRepoImpl();
	ArrayList listOfBookings = new ArrayList();
        
        public void book(Connection connection, int customerID, int sessionID){
             
             Booking book = new Booking();
                     
             // Create a random number generator
             Random rndGenerator = new Random();
             
             int randomNumber = rndGenerator.nextInt(9999);	        
             
             int newBookingID = 1000000 + randomNumber;
             
             book.setBookingID(newBookingID);
             book.setCustomerID(customerID);
             book.setSessionID(sessionID);
             book.setCheckInStatus(false);
             
             listOfBookings.add(book);
             
             BookingRepo.write(connection, "add", book);
        }          

        public String viewAll(){
            String data  = "";
        
            System.out.print("list: " + listOfBookings.size());
            for (int i = 0; i<listOfBookings.size(); i++){
            
                Booking temp = (Booking)listOfBookings.get(i);
                String str = "\n Booking ref numbers: " + temp.getBookingID() +
                                      " for customer: " + temp.getCustomerID() +
                                      " and for session: " + temp.getSessionID();
                data = data + str;
 
            }  
            return data;
        } 
        
        public void setBookingList(ArrayList bookings){
            BookingRepo.setBookings(bookings);
        }
}   
