//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SlopeOperator
//  @ File Name : Customer.java
//  @ Date : 15/02/2017
//  @ Author : Genaro Bedenko
//
//

package slopeoperator;

/*
 *Class for the Customer entity
 *
 * @author Genaro Bedenko
 */
public class Customer {
	private Integer CustomerID;
	private String FirstName;
	private String LastName;
	private String Email;
	private String Telephone;
	public void getID() {
	
	}
	
	public void getName() {
	
	}
	
	public void getLastName() {
	
	}
	
	public void getEmail() {
	
	}
	
	public void getTelephone() {
	
	}
}