//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SlopeOperator
//  @ File Name : Session.java
//  @ Date : 15/02/2017
//  @ Author : Genaro Bedenko
//
//

package slopeoperator;

/*
 *Class for the Session entity
 *
 * @author Genaro Bedenko
 */
public class Session {
	private Integer SessionID;
	private Integer StartTime;
	private Integer EndTime;
	private String SessionType;
	private Integer NoOfPeople;
	private Integer InstructorID;
        
	public void getStartTime() {
	
	}
	
	public void getEndTime() {
	
	}
	
	public void getSessionType() {
	
	}
	
	public void getNumberOfPeople() {
	
	}
	
	public void getInstructorID() {
	
	}
}
