//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SlopeOperator
//  @ File Name : SlopeOperatorUI.java
//  @ Date : 15/02/2017
//  @ Author : Genaro Bedenko
//
//

package slopeoperator;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.*;
import java.sql.*;

/*
 *Class that sets out the user interface
 *
 * @author Genaro Bedenko
 */
public class SlopeOperatorUI {
    
    Connection connection;
    ArrayList list = new ArrayList();
    
    
    BookingController bookingControlerConnection = new BookingController();
    CustomerController customerControllerConnection = new CustomerController();
    
    public SlopeOperatorUI(Connection connectionInput, ArrayList listInput) {
        
        connection = connectionInput;
        bookingControlerConnection.setBookingList(listInput);
    }
        
    private JFrame mainFrame = new JFrame("Sphere Booking & Checking In System - Provided by InvoTech");
    private final JFrame bookingFrame = new JFrame("Booking Session");
    private final JFrame registerFrame = new JFrame("Register a Customer");
    private final JFrame checkInFrame = new JFrame("Check in Customer");
    private final JFrame viewScheduleFrame = new JFrame("View Schedule");
    
    private JLabel headerLabel;
    private JLabel mainStatusLabel;
    
    private JPanel controlPanel;
   
   // Sets up home window user interface
   public void homeWindowSetup(){
      mainFrame = new JFrame("Sphere Booking & Checking In System - Provided by InvoTech");
      mainFrame.setSize(500,500);
      mainFrame.setLayout(new GridLayout(4, 1));

      headerLabel = new JLabel("SLOPE OPERATOR WELCOME SCREEN",JLabel.CENTER );
      mainStatusLabel = new JLabel("Choose a function",JLabel.CENTER);             
      
      mainFrame.addWindowListener(new WindowAdapter() {
         public void windowClosing(WindowEvent windowEvent){
	        System.exit(0);
         }        
      });
      
      controlPanel = new JPanel();
      controlPanel.setLayout(new GridLayout(5, 1));

      JButton registerButton = new JButton("Register a customer");
      JButton bookButton = new JButton("Book a session");
      JButton checkInButton = new JButton("Check in customer");
      JButton viewScheduleButton = new JButton("View Schedule");
      
      registerButton.setActionCommand("Register a customer");
      bookButton.setActionCommand("Book a session");
      checkInButton.setActionCommand("Check in customer");
      viewScheduleButton.setActionCommand("View Schedule");
      
      registerButton.addActionListener(new ButtonClickListener()); 
      bookButton.addActionListener(new ButtonClickListener());
      checkInButton.addActionListener(new ButtonClickListener()); 
      viewScheduleButton.addActionListener(new ButtonClickListener()); 
      
      controlPanel.add(registerButton);
      controlPanel.add(bookButton);
      controlPanel.add(checkInButton);
      controlPanel.add(viewScheduleButton);
     
      mainFrame.add(headerLabel);
      mainFrame.add(controlPanel);
      mainFrame.add(mainStatusLabel);

      mainFrame.setVisible(true);
      bookingFrame.setVisible(false);
      registerFrame.setVisible(false);
   }
   
   // Sets up a window with user interface
   public void setup(JFrame frame, String windowName, String header){
       
      frame = new JFrame(windowName);
      frame.setSize(500,500);
      frame.setLayout(new GridLayout(4, 1));

      headerLabel = new JLabel(header,JLabel.CENTER );
      mainStatusLabel = new JLabel("...",JLabel.CENTER);             
      
      frame.addWindowListener(new WindowAdapter() {
          
         public void windowClosing(WindowEvent windowEvent){
	        System.exit(0);
         }        
      });
      
      controlPanel = new JPanel();
      controlPanel.setLayout(new GridLayout(5, 1));
     
      frame.add(headerLabel);
      frame.add(controlPanel);
      frame.add(mainStatusLabel);

      frame.setVisible(true);
      mainFrame.setVisible(false);
    }

   private void setVisibility(JFrame frame, boolean bool){
      frame.setVisible(bool); 
   }
   
   private class ButtonClickListener implements ActionListener{
      
       public void actionPerformed(ActionEvent e) {
         String command = e.getActionCommand();  
         if( command.equals("Register a customer"))  {
            registerCustomer(); 
         }
         else if( command.equals("Book a session") )  {
            bookSession();           
         }
         else if( command.equals("Check in customer") )  {
            checkInCustomer(); 
         }
         else if(command.equals("View Schedule")) {
            viewSchedule();
         }
      }		
   }
    
    public void registerCustomer() {
        
        String header = "REGISTER A CUSTOMER";
        String windowName = "Register a Customer - Provided by Invotech";
        setup(registerFrame, windowName, header);
        
        registerFrame.addWindowListener(new WindowAdapter() {
          
         public void windowClosing(WindowEvent windowEvent){
	        System.exit(0);
         }        
        });
        
        JButton backButton = new JButton("Back");
        backButton.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
             
             setVisibility(mainFrame, true);
             setVisibility(registerFrame, false);
         }        
        });
          
        controlPanel.add(backButton);
    }
    public void bookSession() {

      mainFrame.setVisible(false);
      
      String header = "BOOK A SESSION";
      String windowTitle = "Book a Session - Provided by InvoTech";
      setup(bookingFrame, windowTitle, header);
      
      
      JLabel  customerIDlabel= new JLabel("Enter the Customer's ID: ", JLabel.CENTER);
      //JRadioButton withInstructorRadioButton = new JRadioButton("With Instructor");
      //JRadioButton withoutInstructorRadioButton = new JRadioButton("Without Instructor");
      JLabel  sessionTypelabel= new JLabel("Enter the Session ID:  ", JLabel.CENTER);
      
      //String[] instructors = { "No Instructor", "A. Adams","B. Barry", "C. Charlie","D. Daniels"};
      
      //JComboBox<String> instructorsDropDown = new JComboBox<String>(instructors);

      //instructorsDropDown.setVisible(true);
    
      //JLabel  dateLabel = new JLabel("Choose Date: ", JLabel.CENTER);
      //JLabel  timeSlotLabel = new JLabel("Choose Time Slot: ", JLabel.CENTER);
      final JTextField customerIDText = new JTextField(6);
      final JTextField sessionIDText = new JTextField(10);
      //final JTextField date = new JTextField(20);      
      //final JTextField timeSlot = new JTextField(20);     

      JButton addButton = new JButton("Book Session");
      addButton.addActionListener(new ActionListener() {
         public void actionPerformed(ActionEvent e) {
            String theCustomerID = customerIDText.getText();
            String theSessionID = sessionIDText.getText();

            int num = Integer.parseInt(theCustomerID);
            int num2 = Integer.parseInt(theSessionID);
            
            bookingControlerConnection.book(connection, num, num2);
            
            String data = "A session has been booked for customer: " + customerIDText.getText();
            data += ", for session number: " + sessionIDText.getText();
            
            mainStatusLabel.setText(data);        
         }        
      });
      
      JButton viewButton = new JButton("View Bookings");
      viewButton.addActionListener(new ActionListener() {
         public void actionPerformed(ActionEvent e) {
                      
            bookingControlerConnection.viewAll();
            
            String data = "Showing all bookings...";
            
            mainStatusLabel.setText(data);        
         }        
      });

      JButton backButton = new JButton("Back");
      backButton.addActionListener(new ActionListener() {
         public void actionPerformed(ActionEvent e) {
             
             setVisibility(mainFrame, true);
             setVisibility(bookingFrame, false);
         }        
      });
      
      controlPanel.add(customerIDlabel);
      controlPanel.add(customerIDText);
      //controlPanel.add(withInstructorRadioButton);
      //controlPanel.add(withoutInstructorRadioButton);
      controlPanel.add(sessionTypelabel);
      controlPanel.add(sessionIDText);
      //controlPanel.add(instructorsDropDown);
      //controlPanel.add(dateLabel);       
      //controlPanel.add(date);
      controlPanel.add(addButton);
      controlPanel.add(viewButton);
      controlPanel.add(backButton); 
    }  
    public void checkInCustomer() {
        
     mainFrame.setVisible(false);
      
      String header = "CHECK-IN CUSTOMER";
      String windowTitle = "Check in Customer - Provided by InvoTech";
      setup(checkInFrame, windowTitle, header);
      
      final JTextField searchCustomer = new JTextField(6);
      JLabel  customerIDlabel= new JLabel("Enter the Customer's ID: ", JLabel.CENTER);
      JButton searchButton = new JButton("Search");
      JButton backButton = new JButton("Back");
      backButton.addActionListener(new ActionListener() {
         public void actionPerformed(ActionEvent e) {
           
             setVisibility(mainFrame, true);
             setVisibility(bookingFrame, false);
         }        
      });
     
      controlPanel.add(customerIDlabel);
      controlPanel.add(searchButton);
      controlPanel.add(backButton); 
    }        
    
    public void viewSchedule() {
        
        String header = "VIEW SCHEDULE";
        String windowName = "View Schedule - Provided by Invotech";
        setup(viewScheduleFrame, windowName, header);
        
        viewScheduleFrame.addWindowListener(new WindowAdapter() {
          
        public void windowClosing(WindowEvent windowEvent){
	        System.exit(0);
         }        
        });
        
        JButton backButton = new JButton("Back");
        backButton.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
             
             setVisibility(mainFrame, true);
             setVisibility(viewScheduleFrame, false);
         }        
        });
          
        controlPanel.add(backButton); 
    }
}
