//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Session.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Session {
	private Object Id;
	private Object TimeStart;
	private Object EndTime;
	public Object nrOfPeople;
	public Object SlopeID;
	public Object InstructorID;
	public Object date;
	public void getId() {
	
	}
	
	public void getStartTime() {
	
	}
	
	public void getEndTime() {
	
	}
	
	public void getDate() {
	
	}
	
	public void getSlopeId() {
	
	}
	
	public void getinstructorId() {
	
	}
}
