//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : InstructorGUI.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class InstructorGUI {
	private Object Id;
	private Object Name;
}
