//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : manager.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class manager {
	private Object Session control;
}
