//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ViewSchedule(Controller).java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class ViewSchedule(Controller) {
	public Session list;
	public void ViewSchedule() {
	
	}
}
