//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Booking Controller.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//
package bookingsession;

import java.util.*;

public class BookingController {
    
	ArrayList list = new ArrayList();
         
         public void book(int customerID, int sessionID){
             
             Booking book = new Booking();
             book.setCustomerID(customerID);
             book.setSessionID(sessionID); 
             
             list.add(book);
         }          

        public String viewAll(){
        String data  = "";
        
        System.out.print("list: " + list.size());
        for (int i = 0; i<list.size(); i++){
            
                Booking temp = (Booking)list.get(i);
                String str = "\n Dentist ref no: " + temp.getCustomerID() + " name: " + temp.getSessionID();
                data = data + str;
 
            }  
            return data;
         } 
}   
