//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Instructor.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Instructor
{
   public int id;
   public String name;
   public int age;
   public String specialty;
   public String personalStatement;
}
