//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ManagerUI.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class ManagerUI
{
   public SessionController control;
   public Menu menu;
   public int choice;
   public void viewMenu()
   {
   
   }
   
   public void seeResults()
   {
   
   }
}
