//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Menu.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Menu
{
   public SessionController options;
   public void displayOptions()
   {
   
   }
}
