//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Slope.java
//  @ Date : 15/02/2017
//  @ Author : 
//
//




public class Slope
{
   public int id;
   public String name;
   public int length;
}
