//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Manager
//  @ File Name : ManagerUI.java
//  @ Date : 15/02/2017
//  @ Author : Genaro Bedenko
//
//

package manager;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.*;

/*
 *Class that sets out the user interface
 *
 * @author Genaro Bedenko
 */
public class ManagerUI {
        
    private JFrame mainFrame = new JFrame("Sphere Booking & Checking In System - Provided by InvoTech");
    private JLabel headerLabel;
    private JLabel mainStatusLabel;
    private JLabel statusLabel;
    private JPanel controlPanel;
              
    public ManagerUI() {
    }

    
   public void setup(){
      mainFrame = new JFrame("Sphere Booking & Checking In System - Provided by InvoTech");
      mainFrame.setSize(500,500);
      mainFrame.setLayout(new GridLayout(4, 1));

      headerLabel = new JLabel("",JLabel.CENTER );
      mainStatusLabel = new JLabel("",JLabel.CENTER);        

      mainStatusLabel.setSize(400,400);
      
      
      mainFrame.addWindowListener(new WindowAdapter() {
         public void windowClosing(WindowEvent windowEvent){
	        System.exit(0);
         }        
      });    
      controlPanel = new JPanel();
      controlPanel.setLayout(new GridLayout(5, 1));

      mainFrame.add(headerLabel);
      mainFrame.add(controlPanel);
      mainFrame.add(mainStatusLabel);      
      mainFrame.setVisible(true);  
      
      mainFrame.setVisible(true);
   }
    
   public void setup(JFrame frame){
      frame.setSize(500,500);
      frame.setLayout(new GridLayout(4, 1));

      headerLabel = new JLabel("",JLabel.CENTER);
      statusLabel = new JLabel("",JLabel.CENTER);        

      statusLabel.setSize(350,100);
      
      
      frame.addWindowListener(new WindowAdapter() {
         public void windowClosing(WindowEvent windowEvent){
	        System.exit(0);
         }        
      });    
      controlPanel = new JPanel();
      controlPanel.setLayout(new GridLayout(4, 1));

      frame.add(headerLabel);
      frame.add(controlPanel);
      frame.add(statusLabel);      
      frame.setVisible(true);  
      
      frame.setVisible(true);
   }

   private void setVisibility(JFrame frame, boolean bool){
      frame.setVisible(bool); 
   }
   
   public void showEventDemo(){
      setup();
      
      JLabel userText = new JLabel("MANAGER WELCOME SCREEN", SwingConstants.CENTER);

      JButton viewScheduleButton = new JButton("View Schedule");
      JButton addSessionButton = new JButton("Add Session");
      
      viewScheduleButton.setActionCommand("View Schedule");
      addSessionButton.setActionCommand("Add Session");
      
      viewScheduleButton.addActionListener(new ButtonClickListener()); 
      addSessionButton.addActionListener(new ButtonClickListener());
      
      controlPanel.add(userText);
      
      controlPanel.add(addSessionButton);
      controlPanel.add(viewScheduleButton);
     
      mainFrame.setVisible(true);      
   }
   

    private class ButtonClickListener implements ActionListener{
      public void actionPerformed(ActionEvent e) {
         String command = e.getActionCommand();  
         if(command.equals("View Schedule")) {
            viewSchedule();
         }
         else if(command.equals("Add Session")) {
             
             addSession();
         }
      }		
   }
    
    
    public void addSession() {
        
        mainStatusLabel.setText("Add Session clicked.");
    }
    public void viewSchedule() {
        
        mainStatusLabel.setText("View Schedule clicked.");
    }
}
